### ISSUE TITLE
Search with Algolia

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/nicolas-hoizey.com#159]
- [x] Index content
- [x] Search for content with autocomplete

**Comment by nhoizey** [comment]
Settings for indexing:

```yaml
algolia:
  nodes_to_index: "p,li,figcaption,blockquote,th,td"
  files_to_exclude:
    - 404.html
    - index.html
    - search.html
    - offline.html
    - offline-fallback.html
    - about/mentions.html
    - tags/index.html
    - links/index.html
    - tools/*
```
